---
# tasks file for docker-registry
- name: login dockerhub
  docker_login:
    email: "taleb.islem@esprit.tn"
    username: "islemt"
    password: "21461251is"
- name: push to dockerhub
  docker_image:
    name: devops:latest
    repository: islemt/front
    push: yes
    source: local

